### PR TITLE
Fix decoding of html entities (#1361)

### PR DESCRIPTION
**Pull request by reekitconcept**
Previously &nbsp; and html tags were handled, however we need an universal conversion of all html entities.

### CODE REVIEW

**Comment by reekitconcept** [comment]
Note: this has to be tested carefully, especially with regards to how it handles pastes.

I notice that there has been a previous fix for pasting so it should be re-validated. I notice that if I paste an html entity such as "&amp;" it will be now decoded back to plaintext "&" which might be undesirable but probably unavoidable if we support pasting html content.

**Review by sneridagh — APPROVED** [review]
LGTM, although I'd like to have acceptance tests around if possible.

**Comment by reekitconcept** [comment]
> LGTM, although I'd like to have acceptance tests around if possible.

I agree that would be useful. - Can we release without? I have a high priority task which I cannot delay, so it's unlikely for me to land this today.

**Comment by sneridagh** [comment]
@ThomasKindermann maybe you can take a look at the cypress tests? thx!

**Comment by sneridagh** [comment]
@ThomasKindermann I fixed the test fixtures. Just to be clear, I'd like to have more accurate acceptance test for the use case that we are fixing. Thanks!

**Comment by ThomasKindermann** [comment]
@sneridagh Ill take a look at the tests

**Pull request merged**
